import 'package:flutter/material.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedYouPeopleWidget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedFollowsanewcoupleandtheirfamilieswhofindthemselvesexami.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedMoviesWidget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedComedyRomanceWidget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedStar1Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/Generated55Widget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedOrderTicketsWidget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedMV5BZTVhMmY1MjctN2U0OC00ZWU4LTgxZDUtYmVhNDE1ODMwMWUwXkE.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/GeneratedTrailerWidget.dart';
import 'package:flutterapp/movie_20appapp/generatedgroup2widget/generated/Generated157HWidget.dart';

/* Group Group 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 206.0,
      height: 428.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 206.0,
              height: 427.0,
              child: GeneratedRectangle1Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 213.0,
              right: null,
              bottom: null,
              width: 206.0,
              height: 214.0,
              child: GeneratedRectangle6Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 206.0,
              height: 214.0,
              child:
                  GeneratedMV5BZTVhMmY1MjctN2U0OC00ZWU4LTgxZDUtYmVhNDE1ODMwMWUwXkE(),
            ),
            Positioned(
              left: 0.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 55.0,
              height: 23.0,
              child: GeneratedMoviesWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 214.0,
              right: null,
              bottom: null,
              width: 206.0,
              height: 214.0,
              child: GeneratedRectangle7Widget(),
            ),
            Positioned(
              left: 3.0,
              top: 223.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 12.0,
              child: Generated157HWidget(),
            ),
            Positioned(
              left: 36.0,
              top: 224.0,
              right: null,
              bottom: null,
              width: 96.0,
              height: 14.0,
              child: GeneratedComedyRomanceWidget(),
            ),
            Positioned(
              left: 133.0,
              top: 227.0,
              right: null,
              bottom: null,
              width: 9.0,
              height: 8.0,
              child: GeneratedStar1Widget(),
            ),
            Positioned(
              left: 145.0,
              top: 226.0,
              right: null,
              bottom: null,
              width: 22.0,
              height: 13.0,
              child: Generated55Widget(),
            ),
            Positioned(
              left: 172.0,
              top: 225.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 16.0,
              child: GeneratedTrailerWidget(),
            ),
            Positioned(
              left: 12.0,
              top: 256.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 21.0,
              child: GeneratedYouPeopleWidget(),
            ),
            Positioned(
              left: 10.0,
              top: 285.0,
              right: null,
              bottom: null,
              width: 194.0,
              height: 63.0,
              child:
                  GeneratedFollowsanewcoupleandtheirfamilieswhofindthemselvesexami(),
            ),
            Positioned(
              left: 65.0,
              top: 374.0,
              right: null,
              bottom: null,
              width: 68.0,
              height: 19.0,
              child: GeneratedRectangle8Widget(),
            ),
            Positioned(
              left: 71.0,
              top: 379.0,
              right: null,
              bottom: null,
              width: 58.0,
              height: 16.0,
              child: GeneratedOrderTicketsWidget(),
            )
          ]),
    ));
  }
}
